### ISSUE TITLE
找到一个小错误

### ISSUE THREAD

**Issue by xmengnet** [levinit/itnotes#1]
https://github.com/levinit/itnotes/blob/main/linux/laptop%E7%AC%94%E8%AE%B0%E6%9C%AC%E7%9B%B8%E5%85%B3.md#%E7%94%B5%E6%BA%90%E7%9B%B8%E5%85%B3%E8%A1%8C%E4%B8%BA%E7%9A%84%E5%93%8D%E5%BA%94%E5%8A%A8%E4%BD%9C
里面的suspend单词拼错了吧

![supspend](https://i.imgur.com/HQ0hobG.png)

**Comment by levinit** [comment]
@xmengnet [xmengnet](https://github.com/xmengnet)  是的，写错了
