### ISSUE TITLE
建议添加zsh，搭配oh-my-zsh简直是神器

### ISSUE THREAD

**Issue by LittleCorn127** [levinit/itnotes#1]
用过一次绝对会成为日常敲命令的首选

**Comment by levinit** [comment]
谢谢推荐 zsh很久前就知道了 oh my zsh 也经常看到吧友/群友提到 我看过一些介绍 了解过这个shell 我只算业余linux爱好者 shell用的不多 敲命令也是些不太复杂的 还是用我的bash😄  tg的linux群组还算活跃 还有irc的 linux吧  可以互相交流哦

**Comment by LittleCorn127** [comment]
oh my zsh这么好的东西为什么不试试呢，补全功能比bash强大多了，还有git插件实在方便啊
